function showDetail(id){var it=null;for(var i=0;i<state.list.length;i++){if(state.list[i].id===id){it=state.list[i];break}}
if(!it){toast('Produit introuvable');location.hash='#/';return}
var type=it.type||'Logiciel';var os=osInfo(it.os);var steps=String(it.install||'').split(/\n+/).map(function(s){return s.trim()}).filter(Boolean);
var html='<a class="detail-back" href="#/" onclick="goHome(event)"><svg class="ni ni-sm"><use href="#i-back"></use></svg> Retour à la liste</a><div class="detail-grid"><div><div class="d-cover">'+coverHTML(it)+'</div><div class="d-actions"><a class="btn primary big" href="'+esc(it.link)+'" target="_blank" rel="noopener"><svg class="ni"><use href="#i-cart"></use></svg> Acheter / Télécharger</a><button class="btn ghost" id="btnCopy" type="button"><svg class="ni ni-sm"><use href="#i-copy"></use></svg> Copier le lien</button></div></div><div><div class="d-badges"><span class="cat">'+esc(it.category||'Autre')+'</span><span style="padding:6px 14px;border-radius:999px;background:'+(type==='Application'?'rgba(124,58,237,.85)':'rgba(37,99,235,.85)')+';color:#fff;font-weight:700;font-size:.78rem">'+esc(type)+'</span><span style="display:inline-flex;align-items:center;gap:7px"><svg class="ni ni-sm" style="color:'+os.c+';filter:none"><use href="'+os.ic+'"></use></svg>'+esc(it.os||'Autre')+'</span><span>Version '+esc(it.version||'—')+'</span><span>'+esc(it.size||'—')+'</span></div><h1 class="d-title">'+esc(it.name)+'</h1><div class="d-rep"><div class="stars">'+starsHTML(it.rate)+'</div><span style="color:var(--muted);font-size:.85rem">'+esc(it.dl||0)+' téléchargements</span></div><div class="d-price"><svg class="ni"><use href="#i-tag"></use></svg> '+esc(it.price||'—')+'</div><div class="d-section"><h2><svg class="ni"><use href="#i-info"></use></svg> Informations</h2><p>'+esc(it.info||'Aucune information fournie.')+'</p></div>';
if(steps.length){html+='<div class="d-section"><h2><svg class="ni"><use href="#i-tool"></use></svg> Mode d\'installation</h2><ol class="steps">'+steps.map(function(s){return '<li>'+esc(s)+'</li>'}).join('')+'</ol></div>'}
html+='</div></div>';gid('detailBox').innerHTML=html;
bind('btnCopy','click',function(){if(navigator.clipboard){navigator.clipboard.writeText(location.href).then(function(){toast('Lien copié ✓')})}else{toast('Copie impossible')}})}
function doLogout(){state.authed=false;sessDel('lg_admin');renderAdmin();toast('Déconnecté')}
function doReset(){if(confirm('Restaurer les données d\'origine ?')){storeDel(DB_KEY);location.hash='#/';location.reload()}}
function doExport(){var blob=new Blob([JSON.stringify(state.list,null,2)],{type:'application/json'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='logiciels.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(a.href);toast('logiciels.json exporté ⬇️')}
function doImportChange(input){var f=input.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var j=JSON.parse(r.result);if(Array.isArray(j)){state.list=j;saveDB();renderAdminList();fillCatList();renderCats();toast('Import réussi ✓')}}catch(err){toast('JSON invalide')}};r.readAsText(f);input.value=''}
function onFileChange(input){var f=input.files[0];if(!f)return;var r=new FileReader();r.onload=function(){gid('f-image').value=r.result;updatePreview()};r.readAsDataURL(f);input.value=''}
function updatePreview(){var v=gid('f-image').value.trim();gid('f-preview').hidden=!v;if(v){gid('f-preview').querySelector('img').src=v}}
function doSubmit(){var data={name:gid('f-name').value.trim(),type:gid('f-type').value,category:gid('f-cat').value.trim()||'Autre',os:gid('f-os').value,version:gid('f-version').value.trim(),size:gid('f-size').value.trim(),dl:parseInt(gid('f-dl').value,10)||0,rate:parseFloat(gid('f-rate').value)||4.5,price:gid('f-price').value.trim(),link:gid('f-link').value.trim(),image:gid('f-image').value.trim(),info:gid('f-info').value.trim(),install:gid('f-install').value.trim()};
if(!data.name||!data.link||!data.price){toast('Nom, prix et lien obligatoires');return false}
if(state.editingId){for(var i=0;i<state.list.length;i++){if(state.list[i].id===state.editingId){for(var k in data){state.list[i][k]=data[k]}break}}toast('Modifié ✓')}else{data.id='s'+Date.now();data.date=new Date().toISOString().slice(0,10);state.list.unshift(data);toast('Produit publié 🎉')}
saveDB();resetForm();renderAdminList();fillCatList();renderCats();return false}
function resetForm(){state.editingId=null;gid('softForm').reset();gid('f-preview').hidden=true;gid('formTitleText').textContent='Ajouter un produit';gid('btnSubmitText').textContent='Publier';gid('btnCancel').hidden=true}
function renderAdmin(){gid('adminLogin').hidden=state.authed;gid('adminPanel').hidden=!state.authed;if(state.authed){renderAdminList();fillCatList()}}
function fillCatList(){var seen={},out='';state.list.forEach(function(i){var c=i.category||'Autre';if(!seen[c]){seen[c]=1;out+='<option value="'+esc(c)+'">'}});gid('catList').innerHTML=out}
function renderAdminList(){var q=(gid('adminSearch')?gid('adminSearch').value:'').toLowerCase();var items=state.list.filter(function(it){if(!q)return true;return(it.name||'').toLowerCase().indexOf(q)>-1||(it.category||'').toLowerCase().indexOf(q)>-1||(it.type||'').toLowerCase().indexOf(q)>-1});gid('listCount').textContent=items.length;gid('adminList').innerHTML=items.map(function(it){var thumb=it.image?'<img src="'+esc(it.image)+'" alt="">':esc(initials(it.name));return '<div class="a-row"><div class="a-thumb cg'+(hashN(it.name)%5)+'">'+thumb+'</div><div class="a-info"><b>'+esc(it.name)+'</b><span>'+esc(it.type||'Logiciel')+' • '+esc(it.os||'—')+' • '+esc(it.category||'Autre')+'</span></div><span class="a-price">'+esc(it.price||'—')+'</span><div class="a-actions"><button data-edit="'+esc(it.id)+'" type="button"><svg class="ni ni-sm"><use href="#i-edit"></use></svg> Modifier</button><button data-del="'+esc(it.id)+'" class="del" type="button"><svg class="ni ni-sm" style="color:#fca5a5;filter:drop-shadow(0 0 4px rgba(244,63,94,.7))"><use href="#i-trash"></use></svg> Suppr.</button></div></div>'}).join('')||'<p style="color:var(--muted)">Aucun produit trouvé.</p>'}
function showView(name){gid('view-home').hidden=name!=='home';gid('view-detail').hidden=name!=='detail';gid('view-admin').hidden=name!=='admin';window.scrollTo(0,0)}
function router(){try{var h=location.hash;if(h.indexOf('#/logiciel/')===0){showView('detail');showDetail(h.slice(11))}else if(h==='#/admin'){showView('admin');renderAdmin()}else{showView('home');renderSeg();renderCats();renderGrid()}}catch(err){toast('⚠️ Erreur router : '+err.message)}}
bind('grid','click',function(e){var card=e.target.closest('[data-open]');if(card){location.hash='#/logiciel/'+card.getAttribute('data-open')}});
bind('segType','click',function(e){var b=e.target.closest('button');if(!b)return;state.type=b.getAttribute('data-type');renderSeg();renderGrid()});
bind('search','input',function(e){state.query=e.target.value;if(location.hash&&location.hash!=='#/'){location.hash='#/'}renderGrid()});
function catClick(e){var a=e.target.closest('[data-cat]');if(!a)return;e.preventDefault();pickCat(a.getAttribute('data-cat'))}
bind('catsNav','click',catClick);bind('mmCats','click',catClick);
bind('adminList','click',function(e){var ed=e.target.closest('[data-edit]'),dl=e.target.closest('[data-del]');
if(ed){var it=null;for(var i=0;i<state.list.length;i++){if(state.list[i].id===ed.getAttribute('data-edit')){it=state.list[i];break}}
if(!it)return;state.editingId=it.id;gid('f-name').value=it.name||'';gid('f-type').value=it.type||'Logiciel';gid('f-cat').value=it.category||'';gid('f-os').value=it.os||'Windows';gid('f-version').value=it.version||'';gid('f-size').value=it.size||'';gid('f-dl').value=it.dl||'';gid('f-rate').value=(it.rate!=null?it.rate:'');gid('f-price').value=it.price||'';gid('f-link').value=it.link||'';gid('f-image').value=it.image||'';gid('f-info').value=it.info||'';gid('f-install').value=it.install||'';updatePreview();gid('formTitleText').textContent='Modifier : '+it.name;gid('btnSubmitText').textContent='Enregistrer';gid('btnCancel').hidden=false;gid('softForm').scrollIntoView({behavior:'smooth'})}
if(dl&&confirm('Supprimer ce produit ?')){state.list=state.list.filter(function(x){return x.id!==dl.getAttribute('data-del')});saveDB();renderAdminList();renderCats();toast('Supprimé 🗑️')}});
document.addEventListener('keydown',function(e){var t=document.activeElement?document.activeElement.tagName:'';if(e.key==='/'&&t!=='INPUT'&&t!=='TEXTAREA'&&t!=='SELECT'){e.preventDefault();gid('search').focus()}});
window.addEventListener('hashchange',router);
if(storeGet('lg_theme')==='light'){document.body.classList.add('light')}
applyThemeIcon();loadDB(function(){router()});