c = open('index.html', encoding='utf-8').read()
c = c.replace('Logipluss', 'Logiciels')
c = c.replace('logipluss', 'logiciels')
c = c.replace('data-type="Logiplus"', 'data-type="Logiciel"')
c = c.replace('value="Logiplus"', 'value="Logiciel"')
c = c.replace('>Logiplus</option>', '>Logiciel</option>')
c = c.replace('Rechercher un logiplus', 'Rechercher un logiciel')
open('index.html', 'w', encoding='utf-8').write(c)
print('OK - fixes appliqués')
