css = open('hero.css', encoding='utf-8').read()
css = css.replace('.devwrap{position:relative;width:min(310px,84%);', '.devwrap{position:relative;width:min(440px,94%);')
css = css.replace('aspect-ratio:4/3;border-radius:26px;', 'aspect-ratio:16/10;border-radius:26px;')
css = css.replace('.mhead{display:flex;align-items:center;gap:8px;padding:14px 10px 8px;', '.mhead{display:flex;align-items:center;gap:8px;padding:10px 10px 6px;')
css = css.replace('.mava{width:26px;height:26px;', '.mava{width:22px;height:22px;')
css = css.replace('.mbody{flex:1;padding:8px 8px 4px;display:flex;flex-direction:column;gap:6px;overflow:hidden}', '.mbody{flex:1;min-height:0;padding:6px 8px 2px;display:flex;flex-direction:column;gap:5px;overflow:hidden}')
css = css.replace('font-size:.52rem;line-height:1.4;', 'font-size:.55rem;line-height:1.35;')
css = css.replace('.minput{display:flex;align-items:center;gap:6px;margin:6px 8px 12px;padding:6px 10px;', '.minput{display:flex;align-items:center;gap:6px;margin:4px 8px 10px;padding:5px 10px;')
open('hero.css', 'w', encoding='utf-8').write(css)
print('OK - tablette lehibe + chat tsy takona')
